### ISSUE TITLE
Inconsistent UI to download artefacts.

### ISSUE THREAD

**Issue by oleg-andreyev** [actions/download-artifact#75] opened 2020-12-24 20:25 UTC
Example:
https://github.com/oleg-andreyev/MinkPhpWebDriver/runs/1606431104
![image](https://user-images.githubusercontent.com/1244112/103105464-af68ee80-4636-11eb-857b-b02ea4735017.png)

vs

https://github.com/oleg-andreyev/MinkPhpWebDriver/runs/1606431104?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1244112/103105475-c7407280-4636-11eb-808d-ddae92322dd2.png)

Notice that "Artifacts" are missing.
The difference only is `check_suite_focus`, it's quite inconsistent to download artifacts.

**Comment by konradpabjan** [comment] 2021-01-04 19:05
Thanks for opening this issue! We recently did some major changes to our UI and this looks like a regression.

As a workaround though, you can click on the `Summary` button and that will show you all the available artifacts:

![image](https://user-images.githubusercontent.com/16109154/103569332-654dfb80-4ec7-11eb-9fdf-75e1087a0fd5.png)

At the bottom you will see:

![image](https://user-images.githubusercontent.com/16109154/103569399-7c8ce900-4ec7-11eb-9e94-fffc63a791a9.png)

You can also use a new link to access them: https://github.com/oleg-andreyev/MinkPhpWebDriver/actions/runs/442938394#artifacts

You can get a link or auto-jump to the artifact you can click on the artifact number at the top of the summary 
![image](https://user-images.githubusercontent.com/16109154/103569705-0fc61e80-4ec8-11eb-9b17-bb77298bcf23.png)

**Comment by konradpabjan** [comment] 2021-01-05 15:29
We recently did a major overhaul to the actions UI with new things like the visualization graph. There is a separate section for artifacts now that you can access by clicking on "summary".

![image](https://user-images.githubusercontent.com/16109154/103663855-dfd35580-4f71-11eb-9c82-5b0fee77a996.png)

The top screenshot with the artifacts dropdown is considered the "legacy" view. It can still be accessed from a few scenarios like pull requests or by clicking on checks. We do have plans to overhaul that as well and the bottom part is now considered the norm moving forward.

Right now it's inconsistent since not every view has been updated but we just haven't had time to go through everything. We decided on removing this because we need a larger, separate area for artifacts moving forward. Right now you're only limited to downloading a zip with all the artifacts contents but in the future imagine scenarios like browsing the contents of your artifact (file explore sort of UI) and downloading a subset of the files that were uploaded.

Closing this out since it's not specific to the `download-artifact` action and there is nothing we can do in this action about this issue.

**Closed by konradpabjan** 2021-01-05 15:29 UTC

**Comment by oleg-andreyev** [comment] 2021-01-09 19:55
@konradpabjan thanks!
