### ISSUE TITLE
download multiple files at once ?

### ISSUE THREAD

**Issue by medyagh** [actions/download-artifact#26] opened 2020-04-19 01:05 UTC
could we download multiple folders at once ?

```
    - name: Download results 
      continue-on-error: true
      uses: actions/download-artifact@v1
      with:
        name: functional_test_docker_ubuntu
        name: barmetal_test_docker_ubuntu

```

? or do I have to repeat this block if I wanna download 8 folders?

**Comment by xenoterracide** [comment] 2020-04-20 19:41
I would think we'd want

```yaml
with:
  name: [ "foo", "bar" ]
```
but I want this

**Comment by xenoterracide** [comment] 2020-04-20 19:49
duplicate of #6 ?

**Comment by konradpabjan** [comment] 2020-04-28 14:16
Going to close this in favor of https://github.com/actions/download-artifact/issues/6 as it's effectively a duplicate.

Wildcard support to download a subset of artifacts should be ideal.

**Closed by konradpabjan** 2020-04-28 14:16 UTC
Labels: duplicate
